spring.application.name=restapi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=6000

server.port=8082